FROM python:3.12-slim

WORKDIR /ui

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ui.py .

EXPOSE 8501

CMD ["streamlit", "run", "ui.py", "--server.address=0.0.0.0"]