apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
         - name: ollama
           image: ollama/ollama
           command: ["ollama", "serve"]
           ports:
             - containerPort: 11434
           resources:              
             requests:
               memory: "6Gi"
               cpu: "1"
             limits:
               memory: "8Gi"
               cpu: "2"
           volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
      volumes:
        - name: ollama-data
          persistentVolumeClaim:
            claimName: ollama-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: ollama
spec:
  selector:
    app: ollama
  ports:
    - port: 11434
      targetPort: 11434

---
apiVersion: batch/v1
kind: Job
metadata:
  name: ollama-pull-mistral
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: pull-mistral
          image: ollama/ollama
          command: ["sh", "-c", "sleep 10 && ollama pull mistral"]
          env:
          - name: OLLAMA_HOST
            value: http://ollama:11434
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
      volumes:
        - name: ollama-data
          persistentVolumeClaim:
            claimName: ollama-pvc